nadin/models/oauth.py
from authlib.integrations.sqla_oauth2 import OAuth2AuthorizationCodeMixin, OAuth2ClientMixin, OAuth2TokenMixin

from nadin.extensions import db


class OAuth2Client(db.Model, OAuth2ClientMixin):
    __tablename__ = "oauth2_client"

    id = db.Column(db.Integer, primary_key=True)
    hub_id = db.Column(db.Integer, db.ForeignKey("vendor.id", ondelete="CASCADE"), default=1, server_default="1")
    hub = db.relationship("Vendor")


class OAuth2AuthorizationCode(db.Model, OAuth2AuthorizationCodeMixin):
    __tablename__ = "oauth2_code"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"))
    user = db.relationship("User")


class OAuth2Token(db.Model, OAuth2TokenMixin):
    __tablename__ = "oauth2_token"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id", ondelete="CASCADE"))
    user = db.relationship("User")

nadin/oauth/__init__.py
from nadin.oauth import routes  # noqa: F401

nadin/oauth/routes.py
import time
from pathlib import Path

from authlib.integrations.flask_oauth2 import current_token
from authlib.jose import JsonWebKey, KeySet
from flask import Blueprint, current_app, jsonify, redirect, render_template, request, url_for
from flask_login import current_user, login_required, logout_user
from werkzeug.security import gen_salt

from nadin.extensions import db
from nadin.models.hub import UserRoles
from nadin.models.oauth import OAuth2AuthorizationCode, OAuth2Client, OAuth2Token
from nadin.oauth.server import authorization, generate_user_info, require_oauth
from nadin.utils import role_required

bp = Blueprint("oauth", __name__)


@bp.route("", methods=("GET",), strict_slashes=False)
@login_required
@role_required([UserRoles.admin])
def home():
    clients = OAuth2Client.query.all()
    return render_template("oauth/home.html", clients=clients)


def split_by_crlf(s):
    return [v for v in s.splitlines() if v]


@bp.route("/create_client", methods=("POST",))
@login_required
@role_required([UserRoles.admin])
def create_client():
    form = request.form
    client_id = gen_salt(24)
    client = OAuth2Client(client_id=client_id, hub_id=current_user.hub_id)
    # Mixin doesn't set the issue_at date
    client.client_id_issued_at = int(time.time())
    if client.token_endpoint_auth_method == "none":
        client.client_secret = ""
    else:
        client.client_secret = gen_salt(48)
    client_metadata = {
        "client_name": form["client_name"],
        "client_uri": form["client_uri"],
        "grant_types": split_by_crlf(form["grant_type"]),
        "redirect_uris": split_by_crlf(form["redirect_uri"]),
        "response_types": split_by_crlf(form["response_type"]),
        "scope": form["scope"],
        "token_endpoint_auth_method": form["token_endpoint_auth_method"],
    }
    client.set_client_metadata(client_metadata)
    db.session.add(client)
    db.session.commit()
    return redirect(url_for("oauth.home"))


@bp.route("/authorize", methods=("GET", "POST"))
@login_required
def authorize():
    # if request.method == "GET":
    #     try:
    #         grant = authorization.get_consent_grant(end_user=current_user)
    #     except OAuth2Error as error:
    #         flash(error.description, category="error")
    #         return redirect(url_for("main.ShowIndex"))
    #     return render_template("oauth/authorize.html", grant=grant)
    return authorization.create_authorization_response(grant_user=current_user)


@bp.route("/remove_client/<int:client_id>", methods=("POST",))
@login_required
@role_required([UserRoles.admin])
def remove_client(client_id):
    client = OAuth2Client.query.filter_by(id=client_id).first_or_404()
    db.session.delete(client)
    db.session.commit()
    return redirect(url_for("oauth.home"))


@bp.route("/token", methods=("POST",))
def issue_token():
    response = authorization.create_token_response()
    response.headers.add("Access-Control-Allow-Origin", "*")
    return response


@bp.route("/userinfo")
@require_oauth("profile")
def userinfo():
    return jsonify(generate_user_info(current_token.user, current_token.scope))


@bp.route("/.well-known/openid-configuration")
def well_known_openid_configuration():

    response = jsonify(
        {
            "authorization_endpoint": url_for("oauth.authorize", _external=True),
            "token_endpoint": url_for("oauth.issue_token", _external=True),
            "userinfo_endpoint": url_for("oauth.userinfo", _external=True),
            "jwks_uri": url_for("oauth.jwks", _external=True),
            "end_session_endpoint": url_for("oauth.logout", _external=True),
            "id_token_signing_alg_values_supported": ["RS256"],
            "issuer": url_for("oauth.home", _external=True),
            "scopes_supported": [
                "openid",
                "profile",
                "email",
            ],
            "grant_types_supported": [
                "authorization_code",
                "refresh_token",
            ],
            "response_types_supported": [
                "code",
                "token",
                "id_token",
                "code token",
                "code id_token",
                "token id_token",
                "code token id_token",
                "none",
            ],
            "subject_types_supported": ["public"],
            "token_endpoint_auth_methods_supported": [
                "client_secret_post",
                "client_secret_basic",
                "none",
            ],
            "code_challenge_methods_supported": ["S256"],
        }
    )
    response.headers.add("Access-Control-Allow-Origin", "*")
    return response


def load_public_keys():
    public_key_path = Path(current_app.config["OPENID_PUBLIC_KEY"])
    public_key = JsonWebKey.import_key(public_key_path.read_bytes(), {"use": "sig", "alg": "RS256"})
    return KeySet([public_key])


@bp.route("/jwks")
def jwks():
    response = jsonify(load_public_keys().as_dict())
    response.headers.add("Access-Control-Allow-Origin", "*")
    return response


@bp.route("/logout")
def logout():
    if current_user.is_authenticated:
        OAuth2Token.query.filter_by(user_id=current_user.id).delete()
        OAuth2AuthorizationCode.query.filter_by(user_id=current_user.id).delete()
    db.session.commit()
    post_logout_redirect_uri = request.args.get("post_logout_redirect_uri")
    if not post_logout_redirect_uri:
        post_logout_redirect_uri = url_for("auth.login")
    if current_user.is_authenticated:
        logout_user()
    return redirect(post_logout_redirect_uri)

nadin/templates/oauth/authorize.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row my-1">
        <div class="col">
            {{grant.client.client_name}} запрашивает авторизацию:
            <strong>{{ grant.request.scope }}</strong>
        </div>
    </div>

    <form action="" method="post">
        <div class="row">
            <div class="col">
                <button class="btn btn-primary" type="submit">Подтвердить</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

nadin/templates/oauth/home.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    {% for client in clients %}
    <div class="row border-bottom">
        <div class="col">
            {{ client.hub.id }}: {{ client.hub.name }}({{ client.hub.email }})
        </div>
        <div class="col">
            {{ client.client_info|tojson }}
            <br>
            {{ client.client_metadata|tojson }}
        </div>
        <div class="col-auto">
            <form action="{{ url_for('oauth.remove_client', client_id=client.id) }}" method="POST">
                <button type="submit" class="btn btn-danger text-white"
                    onclick="return confirm('Удалить?')">
                    <i class="bi bi-x-lg"></i>
                </button>
            </form>
        </div>
    </div>
    {% endfor %}
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form action="{{url_for('oauth.create_client')}}" method="post">
                <div class="mb-3">
                    <label for="client_name" class="form-label">Client Name</label>
                    <input type="text" class="form-control" id="client_name" name="client_name">
                </div>
                <div class="mb-3">
                    <label for="client_uri" class="form-label">Client URI</label>
                    <input type="url" class="form-control" id="client_uri" name="client_uri">
                </div>
                <div class="mb-3">
                    <label for="scope" class="form-label">Allowed Scope</label>
                    <input type="text" class="form-control" id="scope" name="scope">
                </div>
                <div class="mb-3">
                    <label for="scope" class="form-label">Redirect URIs</label>
                    <textarea class="form-control" id="redirect_uri" name="redirect_uri"></textarea>
                </div>
                <div class="mb-3">
                    <label for="scope" class="form-label">Allowed Grant Types</label>
                    <textarea class="form-control" id="grant_type" name="grant_type"></textarea>
                </div>
                <div class="mb-3">
                    <label for="scope" class="form-label">Allowed Response Types</label>
                    <textarea class="form-control" id="response_type" name="response_type"></textarea>
                </div>
                <div class="mb-3">
                    <select class="form-select" name="token_endpoint_auth_method">
                        <option selected disabled>Token Endpoint Auth Method</option>
                        <option value="client_secret_basic">client_secret_basic</option>
                        <option value="client_secret_post">client_secret_post</option>
                        <option value="none">none</option>
                    </select>
                </div>
                <button class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>



{% endblock %}